name: tactics_fc_generator
description: A comprehensive data generation module for soccer simulation games
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  # Core dependencies for data generation
  json_annotation: ^4.9.0
  
  # Local dependency on the engine module
  tactics_fc_engine:
    path: ../tactics-fc-engine

dev_dependencies:
  # Testing framework
  test: ^1.24.0
  
  # Code generation tools
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  lints: ^2.1.0

# Override dependency to ensure compatibility
dependency_overrides:
  tactics_fc_engine:
    path: ../tactics-fc-engine
